FROM node:18.20.7-alpine3.20 AS base
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN corepack enable pnpm

FROM base AS dependencies
RUN pnpm install

FROM base
COPY . .
COPY --from=dependencies /app/node_modules ./node_modules
RUN pnpm run test