name: Build and Publish Docker Image
on:
  push:
    branches:
      - '**'
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_HOSTNAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        run: docker build -t baseimage:${GITHUB_REF##*/} .

      - name: Tag image
        run: |
          docker tag baseimage:${GITHUB_REF##*/} ${{ secrets.DOCKER_REGISTRY_HOSTNAME }}/${{ vars.IMAGE_NAME }}:${GITHUB_REF##*/}-${{github.run_number}}
          docker tag baseimage:${GITHUB_REF##*/} ${{ secrets.DOCKER_REGISTRY_HOSTNAME }}/${{ vars.IMAGE_NAME }}:${GITHUB_REF##*/}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY_HOSTNAME }}/${{ vars.IMAGE_NAME }}:${GITHUB_REF##*/}-${{github.run_number}}
          docker push ${{ secrets.DOCKER_REGISTRY_HOSTNAME }}/${{ vars.IMAGE_NAME }}:${GITHUB_REF##*/}
